spring:
  profiles:
    active: test
---
server:
  port: 3355
spring:
  profiles: test
  application:
    name: config-client-test
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka
---
server:
  port: 3356
spring:
  profiles: dev
  application:
    name: config-client-dev
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka
