spring:
  profiles:
    active: test
---
server:
  port: 8020 #8020
spring:
  application:
    profiles: test
    name: cunsumer
         # consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30 #续约更新时间间隔(默认30s)
    lease-expiration-duration-in-seconds: 60 #续约到期时间(默认90s)
feign:
  hystrix:
    enabled: true
management: #SpringBoot 2.0 + SpringCloud Finchley 运行Dashboard必须配置
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'
    base-path: /
---
server:
  port: 8020 #8020
spring:
  application:
    profiles: dev
    name: cunsumer
         # consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30 #续约更新时间间隔(默认30s)
    lease-expiration-duration-in-seconds: 60 #续约到期时间(默认90s)
feign:
  hystrix:
    enabled: true
management: #SpringBoot 2.0 + SpringCloud Finchley 运行Dashboard必须配置
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'
    base-path: /