spring:
  profiles:
    active: test
---
server:
  port: 8010
spring:
  profiles: test
  application:
    name: provider-test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
---
server:
  port: 8010
spring:
  application:
    profiles: dev
    name: provider-dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
